# HKEX MBP-1 reconstruction DEBUG

In [1]:
import DestinyResearch as dr

In [2]:
tbl = dr.get_mbp1_front("HSI", "2026-02-03")

[dr] Front month for HSI on 2026-02-03: HSIG26

In [3]:
tbl.shape

(10071753, 13)

In [6]:
df = tbl.to_pandas()

In [7]:
df.columns

Index(['ts_event', 'ts_recv', 'action', 'side', 'price', 'flags', 'sequence',
       'bid_px_00', 'ask_px_00', 'bid_sz_00', 'ask_sz_00', 'bid_ct_00',
       'ask_ct_00'],
      dtype='str')

In [8]:
df[df.bid_px_00 > df.ask_px_00]

,ts_event,ts_recv,action,side,price,flags,sequence,bid_px_00,ask_px_00,bid_sz_00,ask_sz_00,bid_ct_00,ask_ct_00
953,1770081301462000000,1770081301462000000,ADD,ASK,27046.0,132,493222,27050.0,27046.0,4.0,3.0,3.0,1.0
954,1770081301463000000,1770081301463000000,ADD,ASK,27068.0,132,493226,27050.0,27046.0,4.0,3.0,3.0,1.0
955,1770081301460000000,1770081301463000000,TRADE,BID,27046.0,132,493227,27050.0,27046.0,4.0,3.0,3.0,1.0
956,1770081301460000000,1770081301463000000,TRADE,BID,27046.0,132,493230,27050.0,27046.0,4.0,3.0,3.0,1.0
957,1770081301463000000,1770081301463000000,CANCEL,ASK,0.0,132,493235,27050.0,27046.0,4.0,3.0,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10071748,1770145200013000000,1770145200013000000,ADD,ASK,26684.0,132,160100977,26916.0,26577.0,7.0,1.0,1.0,1.0
10071749,1770145200040000000,1770145200040000000,CANCEL,ASK,0.0,132,160100986,26916.0,26577.0,7.0,1.0,1.0,1.0
10071750,1770145200040000000,1770145200040000000,CANCEL,BID,0.0,132,160100992,26916.0,26577.0,7.0,1.0,1.0,1.0
10071751,1770145200040000000,1770145200040000000,CANCEL,ASK,0.0,132,160100994,26916.0,26577.0,7.0,1.0,1.0,1.0
10071752,1770145200040000000,1770145200040000000,CANCEL,BID,0.0,132,160100997,26916.0,26577.0,7.0,1.0,1.0,1.0

In [14]:
df.loc[0:10]

,ts_event,ts_recv,action,side,price,flags,sequence,bid_px_00,ask_px_00,bid_sz_00,ask_sz_00,bid_ct_00,ask_ct_00
0,1770066427752000000,1770066427752000000,ADD,BID,26915.0,132,149,26915.0,NaN,2.0,NaN,1.0,NaN
1,1770066427752000000,1770066427752000000,ADD,BID,26912.0,132,150,26915.0,NaN,2.0,NaN,1.0,NaN
2,1770066427752000000,1770066427752000000,ADD,BID,26900.0,132,151,26915.0,NaN,2.0,NaN,1.0,NaN
3,1770066427752000000,1770066427752000000,ADD,BID,26900.0,132,152,26915.0,NaN,2.0,NaN,1.0,NaN
4,1770066427752000000,1770066427752000000,ADD,BID,26860.0,132,153,26915.0,NaN,2.0,NaN,1.0,NaN
5,1770066427752000000,1770066427752000000,ADD,BID,26855.0,132,154,26915.0,NaN,2.0,NaN,1.0,NaN
6,1770066427752000000,1770066427752000000,ADD,BID,26850.0,132,155,26915.0,NaN,2.0,NaN,1.0,NaN
7,1770066427752000000,1770066427752000000,ADD,BID,26844.0,132,156,26915.0,NaN,2.0,NaN,1.0,NaN
8,1770066427752000000,1770066427752000000,ADD,BID,26828.0,132,157,26915.0,NaN,2.0,NaN,1.0,NaN
9,1770066427752000000,1770066427752000000,ADD,BID,26811.0,132,158,26915.0,NaN,2.0,NaN,1.0,NaN
10,1770066427752000000,1770066427752000000,ADD,BID,26806.0,132,159,26915.0,NaN,2.0,NaN,1.0,NaN